queueName: your-queue-name
deadLetterQueueName: your-deadletter-queue-name
region: your-region-name
accessKeyId: your-aws-access-key
secretAccessKey: your-aws-access-secrect
workerLambdaName: your-worker-lambda-name